from __future__ import print_function

import json
import os
import time


class ExpansionDataCollector(object):
    def __init__(self, result_folder, run_params, target_mols=None):
        self.data_dir = os.path.join(result_folder, "expansion_data")
        os.makedirs(self.data_dir, exist_ok=True)

        self.node_expansion_path = os.path.join(self.data_dir, "node_expansions.jsonl")
        self.reaction_candidate_path = os.path.join(self.data_dir, "reaction_candidates.jsonl")
        self.metadata_path = os.path.join(self.data_dir, "metadata.json")

        self._node_f = open(self.node_expansion_path, "w", encoding="utf-8", buffering=1)
        self._reaction_f = open(self.reaction_candidate_path, "w", encoding="utf-8", buffering=1)

        metadata = {
            "created_at": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),
            "run_params": run_params,
            "target_count": len(target_mols or []),
            "targets": list(target_mols or []),
            "files": {
                "node_expansions": self.node_expansion_path,
                "reaction_candidates": self.reaction_candidate_path,
            },
            "schema": {
                "node_expansions": "One line per selected search-tree molecule expansion.",
                "reaction_candidates": "One line per one-step model candidate reaction generated by an expansion.",
            },
        }
        with open(self.metadata_path, "w", encoding="utf-8") as handle:
            json.dump(self._json_ready(metadata), handle, ensure_ascii=False, indent=2, sort_keys=True)

    def record_node_expansion(
        self,
        target_id,
        target_mol,
        iteration,
        expanded_mol_node,
        search_status,
        root_succ_value,
        num_model_candidates,
        num_valid_candidates,
        num_expected_added_candidates,
        failure_reason=None,
    ):
        record = {
            "target_id": int(target_id),
            "target_mol": target_mol,
            "iteration": int(iteration),
            "expanded_mol": expanded_mol_node.mol,
            "expanded_mol_id": int(expanded_mol_node.id),
            "expanded_mol_depth": int(expanded_mol_node.depth),
            "reaction_depth": int(expanded_mol_node.depth + 1),
            "search_status": search_status,
            "root_succ_value": root_succ_value,
            "num_model_candidates": int(num_model_candidates),
            "num_valid_candidates": int(num_valid_candidates),
            "num_expected_added_candidates": int(num_expected_added_candidates),
            "failure_reason": failure_reason,
        }
        self._write_jsonl(self._node_f, record)

    def record_reaction_candidate(self, record):
        self._write_jsonl(self._reaction_f, record)

    def close(self):
        for handle in (self._node_f, self._reaction_f):
            try:
                handle.close()
            except Exception:
                pass

    def _write_jsonl(self, handle, record):
        handle.write(json.dumps(self._json_ready(record), ensure_ascii=False, sort_keys=True) + "\n")

    def _json_ready(self, value):
        if value is None:
            return None
        if isinstance(value, (str, bool, int)):
            return value
        if isinstance(value, float):
            if value == float("inf") or value == float("-inf") or value != value:
                return None
            return value
        if isinstance(value, (list, tuple)):
            return [self._json_ready(item) for item in value]
        if isinstance(value, dict):
            return {str(key): self._json_ready(item) for key, item in value.items()}
        try:
            import numpy as np

            if isinstance(value, np.generic):
                return self._json_ready(value.item())
        except Exception:
            pass
        return str(value)
