#!/usr/bin/env python3
"""Render Retro* Graphviz search trees as collapsible HTML pages.

The input files are Graphviz DOT files generated by ``MolTree.viz_search_tree``.
This script converts one file or a directory of files into interactive HTML
pages with expandable/collapsible nodes and per-molecule SVG depictions stored
as separate files on disk.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

from rdkit import Chem
from rdkit.Chem import Draw


NODE_RE = re.compile(r'^\s*(?P<node>"(?:[^"\\]|\\.)*"|[^\s\[]+)\s*\[(?P<attrs>.+)\]\s*$')
EDGE_RE = re.compile(
    r'^\s*(?P<src>"(?:[^"\\]|\\.)*"|[^\s]+)\s*->\s*(?P<dst>"(?:[^"\\]|\\.)*"|[^\s]+)\s*'
    r'\[(?P<attrs>.+)\]\s*$'
)
ATTR_RE = re.compile(r'(\w+)=("[^"]*"|[^\s\]]+)')
TARGET_NAME_RE = re.compile(r'^mol_.*_search_tree$')


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Convert Retro* search-tree DOT files into collapsible HTML pages. "
            "If the input is a directory, all files named like mol_*_search_tree "
            "are converted."
        )
    )
    parser.add_argument("input", help="Input DOT file or directory containing DOT files.")
    parser.add_argument(
        "-o",
        "--output-dir",
        help=(
            "Directory to write HTML files into. Defaults to <input>/interactive_html "
            "for directory input, or the input file's parent directory for single-file input."
        ),
    )
    return parser.parse_args()


def _unquote(token: str) -> str:
    token = token.strip()
    if token.startswith('"') and token.endswith('"'):
        token = token[1:-1]
        token = token.replace(r"\"", '"')
    return token


def _parse_attrs(attr_string: str) -> Dict[str, str]:
    attrs: Dict[str, str] = {}
    for key, value in ATTR_RE.findall(attr_string):
        attrs[key] = _unquote(value)
    return attrs


def _truncate(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return text[: limit - 1] + "..."


def _wrap_text(text: str, width: int) -> List[str]:
    if not text:
        return [""]
    words = text.split()
    if len(words) == 1 and len(text) <= width:
        return [text]

    lines: List[str] = []
    current = ""
    for word in words if len(words) > 1 else [text[i : i + width] for i in range(0, len(text), width)]:
        candidate = word if not current else f"{current} {word}"
        if len(candidate) <= width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines[:3]


def _display_lines(node_id: str, shape: str) -> List[str]:
    if shape == "rarrow":
        return [f"R{node_id}"]

    if " | " in node_id:
        step, smiles = node_id.split(" | ", 1)
        return [f"M{step}", *_wrap_text(_truncate(smiles, 84), 28)]
    return _wrap_text(_truncate(node_id, 84), 28)


def _extract_smiles(node_id: str, shape: str) -> str | None:
    if shape != "box":
        return None
    if " | " not in node_id:
        return None
    _, smiles = node_id.split(" | ", 1)
    return smiles


def parse_dot_tree(path: Path) -> Dict[str, object]:
    nodes: Dict[str, Dict[str, object]] = {}
    edges: List[Tuple[str, str, str]] = []

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line in {"digraph G {", "}"}:
            continue
        if line.startswith("rankdir=") or line.startswith("node "):
            continue
        if line.endswith(";"):
            line = line[:-1]

        edge_match = EDGE_RE.match(line)
        if edge_match:
            attrs = _parse_attrs(edge_match.group("attrs"))
            edges.append(
                (
                    _unquote(edge_match.group("src")),
                    _unquote(edge_match.group("dst")),
                    attrs.get("label", ""),
                )
            )
            continue

        node_match = NODE_RE.match(line)
        if node_match:
            node_id = _unquote(node_match.group("node"))
            attrs = _parse_attrs(node_match.group("attrs"))
            shape = attrs.get("shape", "box")
            nodes[node_id] = {
                "id": node_id,
                "shape": shape,
                "color": attrs.get("color", "lightgrey"),
                "label": node_id,
                "displayLines": _display_lines(node_id, shape),
                "title": node_id,
                "smiles": _extract_smiles(node_id, shape),
                "imagePath": None,
                "children": [],
            }
            continue

    if not nodes:
        raise ValueError(f"No nodes parsed from {path}")

    parent_of: Dict[str, str] = {}
    edge_label_to_child: Dict[str, str] = {}
    for src, dst, label in edges:
        if src not in nodes or dst not in nodes:
            continue
        parent_of[dst] = src
        edge_label_to_child[dst] = label
        nodes[src]["children"].append(dst)

    roots = [node_id for node_id in nodes if node_id not in parent_of]
    if not roots:
        raise ValueError(f"Could not find root node in {path}")

    def build(node_id: str) -> Dict[str, object]:
        node = nodes[node_id]
        return {
            "id": node["id"],
            "shape": node["shape"],
            "color": node["color"],
            "title": node["title"],
            "displayLines": node["displayLines"],
            "smiles": node["smiles"],
            "imagePath": node["imagePath"],
            "edgeLabel": edge_label_to_child.get(node_id, ""),
            "children": [build(child_id) for child_id in node["children"]],
        }

    if len(roots) == 1:
        return build(roots[0])

    return {
        "id": "__root__",
        "shape": "box",
        "color": "lightgrey",
        "title": f"{path.name} (synthetic root)",
        "displayLines": [path.name],
        "smiles": None,
        "imagePath": None,
        "edgeLabel": "",
        "children": [build(root_id) for root_id in roots],
    }


def _iter_nodes(node: Dict[str, object]) -> Iterable[Dict[str, object]]:
    yield node
    for child in node.get("children", []):
        yield from _iter_nodes(child)


def _render_smiles_png(smiles: str, output_path: Path) -> bool:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return False

    Chem.rdDepictor.Compute2DCoords(mol)
    image = Draw.MolToImage(mol, size=(280, 180))
    image.save(output_path)
    return True


def materialize_molecule_assets(tree: Dict[str, object], tree_dir: Path) -> None:
    molecules_dir = tree_dir / "molecules"
    molecules_dir.mkdir(parents=True, exist_ok=True)
    seen_smiles: Dict[str, str] = {}

    for node in _iter_nodes(tree):
        smiles = node.get("smiles")
        if not smiles:
            continue

        if smiles not in seen_smiles:
            slug = hashlib.sha1(smiles.encode("utf-8")).hexdigest()[:16]
            mol_dir = molecules_dir / slug
            mol_dir.mkdir(parents=True, exist_ok=True)
            image_path = mol_dir / "mol.png"
            smiles_path = mol_dir / "smiles.txt"
            ok = _render_smiles_png(smiles, image_path)
            if ok:
                smiles_path.write_text(smiles + "\n", encoding="utf-8")
                seen_smiles[smiles] = f"molecules/{slug}/mol.png"
            else:
                seen_smiles[smiles] = ""

        node["imagePath"] = seen_smiles[smiles]


def render_html(tree: Dict[str, object], title: str) -> str:
    data_json = json.dumps(tree, ensure_ascii=False)
    safe_title = html.escape(title)
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{safe_title}</title>
  <style>
    :root {{
      color-scheme: light dark;
      --bg: #0f172a;
      --panel: #111827;
      --panel-border: #334155;
      --text: #e5e7eb;
      --muted: #94a3b8;
      --edge: #64748b;
      --edge-label: #cbd5e1;
      --node-stroke: #0f172a;
      --button-bg: #1e293b;
      --button-hover: #334155;
    }}

    body {{
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: Inter, "Noto Sans SC", "Microsoft YaHei", sans-serif;
    }}

    .toolbar {{
      position: sticky;
      top: 0;
      z-index: 20;
      display: flex;
      gap: 12px;
      align-items: center;
      flex-wrap: wrap;
      padding: 12px 16px;
      border-bottom: 1px solid var(--panel-border);
      background: rgba(15, 23, 42, 0.94);
      backdrop-filter: blur(8px);
    }}

    .toolbar h1 {{
      margin: 0;
      font-size: 16px;
      font-weight: 700;
    }}

    .toolbar .meta {{
      color: var(--muted);
      font-size: 13px;
    }}

    .toolbar button {{
      border: 1px solid var(--panel-border);
      background: var(--button-bg);
      color: var(--text);
      border-radius: 8px;
      padding: 6px 10px;
      cursor: pointer;
      font-size: 13px;
    }}

    .toolbar button:hover {{
      background: var(--button-hover);
    }}

    #viewport {{
      width: 100vw;
      height: calc(100vh - 62px);
      overflow: hidden;
    }}

    svg {{
      width: 100%;
      height: 100%;
      display: block;
      cursor: grab;
    }}

    svg.dragging {{
      cursor: grabbing;
    }}

    .edge {{
      fill: none;
      stroke: var(--edge);
      stroke-width: 1.4;
    }}

    .edge-label {{
      font-size: 12px;
      fill: var(--edge-label);
    }}

    .node rect {{
      stroke: var(--node-stroke);
      stroke-width: 1.2;
      rx: 10;
      ry: 10;
    }}

    .node text {{
      font-size: 12px;
      fill: #111827;
      pointer-events: none;
      font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    }}

    .node.has-children {{
      cursor: pointer;
    }}

    .node .toggle-indicator {{
      font-size: 11px;
      font-weight: 700;
      fill: #0f172a;
    }}

    .legend {{
      margin-left: auto;
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
      color: var(--muted);
      font-size: 12px;
    }}

    .legend span {{
      display: inline-flex;
      align-items: center;
      gap: 6px;
    }}

    .dot {{
      width: 10px;
      height: 10px;
      border-radius: 999px;
      display: inline-block;
    }}
  </style>
</head>
<body>
  <div class="toolbar">
    <h1>{safe_title}</h1>
    <span class="meta">默认折叠，点击节点展开或收起</span>
    <button id="expand-all">全部展开</button>
    <button id="collapse-all">全部收起</button>
    <button id="reset-view">重置视图</button>
    <div class="legend">
      <span><i class="dot" style="background:aquamarine"></i>未完成</span>
      <span><i class="dot" style="background:lightblue"></i>成功</span>
      <span><i class="dot" style="background:lightyellow"></i>已知分子</span>
      <span><i class="dot" style="background:lightgrey"></i>开放节点</span>
    </div>
  </div>
  <div id="viewport">
    <svg id="tree-svg" viewBox="0 0 1200 800" xmlns="http://www.w3.org/2000/svg">
      <g id="scene"></g>
    </svg>
  </div>

  <script>
    const root = {data_json};
    const svg = document.getElementById("tree-svg");
    const scene = document.getElementById("scene");
    const MOL_WIDTH = 280;
    const MOL_HEIGHT = 230;
    const REACTION_WIDTH = 160;
    const REACTION_HEIGHT = 66;
    const H_GAP = 120;
    const V_GAP = 28;
    const MARGIN_X = 50;
    const MARGIN_Y = 40;

    const state = {{
      scale: 1,
      tx: 20,
      ty: 20,
      dragging: false,
      dragX: 0,
      dragY: 0,
    }};

    function initializeCollapsed(node, isRoot = false) {{
      node.expanded = false;
      node.visibleChildren = [];
      if (Array.isArray(node.children)) {{
        for (const child of node.children) {{
          initializeCollapsed(child, false);
        }}
      }}
      if (isRoot) {{
        node.expanded = false;
      }}
    }}

    function setExpandedRecursive(node, expanded) {{
      node.expanded = expanded;
      for (const child of node.children || []) {{
        setExpandedRecursive(child, expanded);
      }}
    }}

    function visibleChildren(node) {{
      return node.expanded ? (node.children || []) : [];
    }}

    function nodeWidth(node) {{
      return node.shape === "box" ? MOL_WIDTH : REACTION_WIDTH;
    }}

    function nodeHeight(node) {{
      return node.shape === "box" ? MOL_HEIGHT : REACTION_HEIGHT;
    }}

    function computeLayout(node, depth, nextY) {{
      const children = visibleChildren(node);
      node.depth = depth;
      node.width = nodeWidth(node);
      node.height = nodeHeight(node);
      node.x = MARGIN_X + depth * (MOL_WIDTH + H_GAP);

      if (children.length === 0) {{
        node.y = nextY.value;
        nextY.value += node.height + V_GAP;
        return;
      }}

      for (const child of children) {{
        computeLayout(child, depth + 1, nextY);
      }}
      const first = children[0];
      const last = children[children.length - 1];
      node.y = (first.y + last.y) / 2;
    }}

    function flattenVisible(node, nodes = [], edges = []) {{
      nodes.push(node);
      for (const child of visibleChildren(node)) {{
        edges.push({{ parent: node, child }});
        flattenVisible(child, nodes, edges);
      }}
      return {{ nodes, edges }};
    }}

    function escapeXml(text) {{
      return text
        .replaceAll("&", "&amp;")
        .replaceAll("<", "&lt;")
        .replaceAll(">", "&gt;");
    }}

    function updateTransform() {{
      scene.setAttribute("transform", `translate(${{state.tx}}, ${{state.ty}}) scale(${{state.scale}})`);
    }}

    function render() {{
      const nextY = {{ value: MARGIN_Y }};
      computeLayout(root, 0, nextY);
      const {{ nodes, edges }} = flattenVisible(root);
      const totalWidth = Math.max(...nodes.map(n => n.x + n.width), 0) + 120;
      const totalHeight = Math.max(...nodes.map(n => n.y + n.height), 0) + 120;
      svg.setAttribute("viewBox", `0 0 ${{Math.max(totalWidth, 1200)}} ${{Math.max(totalHeight, 800)}}`);

      const parts = [];
      for (const edge of edges) {{
        const x1 = edge.parent.x + edge.parent.width;
        const y1 = edge.parent.y + edge.parent.height / 2;
        const x2 = edge.child.x;
        const y2 = edge.child.y + edge.child.height / 2;
        const c1 = x1 + 40;
        const c2 = x2 - 40;
        parts.push(
          `<path class="edge" d="M ${{x1}} ${{y1}} C ${{c1}} ${{y1}}, ${{c2}} ${{y2}}, ${{x2}} ${{y2}}" />`
        );
        if (edge.child.edgeLabel) {{
          const lx = (x1 + x2) / 2;
          const ly = (y1 + y2) / 2 - 6;
          parts.push(`<text class="edge-label" x="${{lx}}" y="${{ly}}" text-anchor="middle">${{escapeXml(edge.child.edgeLabel)}}</text>`);
        }}
      }}

      for (const node of nodes) {{
        const classes = ["node"];
        if ((node.children || []).length > 0) {{
          classes.push("has-children");
        }}
        const indicator = (node.children || []).length > 0
          ? `<text class="toggle-indicator" x="${{node.x + node.width - 16}}" y="${{node.y + 18}}" text-anchor="middle">${{node.expanded ? "−" : "+"}}</text>`
          : "";
        const lines = (node.displayLines || []).map((line, index) => {{
          const y = node.shape === "box" ? (node.y + 200 + index * 14) : (node.y + 26 + index * 15);
          return `<text x="${{node.x + 12}}" y="${{y}}">${{escapeXml(line)}}</text>`;
        }}).join("");
        const smilesText = node.smiles
          ? `<text x="${{node.x + 12}}" y="${{node.y + 186}}">${{escapeXml(node.smiles.length > 42 ? node.smiles.slice(0, 41) + "…" : node.smiles)}}</text>`
          : "";
        const imageBlock = node.imagePath
          ? `<image href="${{escapeXml(node.imagePath)}}" x="${{node.x + 10}}" y="${{node.y + 10}}" width="${{node.width - 20}}" height="160" preserveAspectRatio="xMidYMid meet"></image>`
          : "";

        parts.push(`
          <g class="${{classes.join(" ")}}" data-node-id="${{escapeXml(node.id)}}" transform="translate(0,0)">
            <title>${{escapeXml(node.title)}}</title>
            <rect x="${{node.x}}" y="${{node.y}}" width="${{node.width}}" height="${{node.height}}" fill="${{node.color}}"></rect>
            ${{indicator}}
            ${{imageBlock}}
            ${{smilesText}}
            ${{lines}}
          </g>
        `);
      }}

      scene.innerHTML = parts.join("");
      for (const el of scene.querySelectorAll(".node.has-children")) {{
        el.addEventListener("click", () => {{
          const nodeId = el.getAttribute("data-node-id");
          toggleNode(root, nodeId);
          render();
        }});
      }}
      updateTransform();
    }}

    function toggleNode(node, targetId) {{
      if (node.id === targetId) {{
        node.expanded = !node.expanded;
        return true;
      }}
      for (const child of node.children || []) {{
        if (toggleNode(child, targetId)) {{
          return true;
        }}
      }}
      return false;
    }}

    function resetView() {{
      state.scale = 1;
      state.tx = 20;
      state.ty = 20;
      updateTransform();
    }}

    initializeCollapsed(root, true);
    render();
    resetView();

    document.getElementById("expand-all").addEventListener("click", () => {{
      setExpandedRecursive(root, true);
      render();
    }});

    document.getElementById("collapse-all").addEventListener("click", () => {{
      setExpandedRecursive(root, false);
      render();
    }});

    document.getElementById("reset-view").addEventListener("click", () => {{
      resetView();
    }});

    svg.addEventListener("wheel", (event) => {{
      event.preventDefault();
      const factor = event.deltaY < 0 ? 1.08 : 0.92;
      state.scale = Math.min(Math.max(state.scale * factor, 0.35), 3.5);
      updateTransform();
    }}, {{ passive: false }});

    svg.addEventListener("mousedown", (event) => {{
      state.dragging = true;
      svg.classList.add("dragging");
      state.dragX = event.clientX;
      state.dragY = event.clientY;
    }});

    window.addEventListener("mousemove", (event) => {{
      if (!state.dragging) {{
        return;
      }}
      state.tx += event.clientX - state.dragX;
      state.ty += event.clientY - state.dragY;
      state.dragX = event.clientX;
      state.dragY = event.clientY;
      updateTransform();
    }});

    window.addEventListener("mouseup", () => {{
      state.dragging = false;
      svg.classList.remove("dragging");
    }});
  </script>
</body>
</html>
"""


def iter_dot_files(input_path: Path) -> Iterable[Path]:
    if input_path.is_file():
        yield input_path
        return

    if not input_path.is_dir():
        raise FileNotFoundError(f"Input path not found: {input_path}")

    for path in sorted(input_path.iterdir()):
        if path.is_file() and TARGET_NAME_RE.match(path.name):
            yield path


def build_index(output_dir: Path, html_files: List[Path]) -> None:
    links = "\n".join(
        f'<li><a href="{html.escape(path.relative_to(output_dir).as_posix())}">{html.escape(path.parent.name)}</a></li>'
        for path in html_files
    )
    content = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Interactive Search Trees</title>
  <style>
    body {{
      margin: 0;
      padding: 32px;
      font-family: Inter, "Noto Sans SC", sans-serif;
      background: #0f172a;
      color: #e2e8f0;
    }}
    a {{
      color: #7dd3fc;
      text-decoration: none;
    }}
    a:hover {{
      text-decoration: underline;
    }}
    li {{
      margin: 10px 0;
    }}
  </style>
</head>
<body>
  <h1>Interactive Search Trees</h1>
  <p>点击文件名打开对应的可交互 HTML 搜索树。</p>
  <ul>
    {links}
  </ul>
</body>
</html>
"""
    (output_dir / "index.html").write_text(content, encoding="utf-8")


def main() -> None:
    args = parse_args()
    input_path = Path(args.input).expanduser().resolve()
    output_dir = (
        Path(args.output_dir).expanduser().resolve()
        if args.output_dir
        else (input_path.parent if input_path.is_file() else input_path / "interactive_html")
    )
    output_dir.mkdir(parents=True, exist_ok=True)

    html_files: List[Path] = []
    for dot_file in iter_dot_files(input_path):
        tree = parse_dot_tree(dot_file)
        tree_dir = output_dir / dot_file.name
        tree_dir.mkdir(parents=True, exist_ok=True)
        materialize_molecule_assets(tree, tree_dir)
        html_text = render_html(tree, dot_file.name)
        output_file = tree_dir / "index.html"
        output_file.write_text(html_text, encoding="utf-8")
        html_files.append(output_file)
        print(f"[ok] {dot_file} -> {output_file}")

    if not html_files:
        raise SystemExit("No matching search-tree files found.")

    if input_path.is_dir():
        build_index(output_dir, html_files)
        print(f"[ok] index -> {output_dir / 'index.html'}")


if __name__ == "__main__":
    main()
